version: 2

jobs:
    build:
        working_directory: ~/app
        docker:
            - image: circleci/node:7-browsers
        steps:

            ##
            # SETUP
            ##
            - checkout
            - run:
                name: Install node global dependencies
                command: |
                  which chrome
                  which Chrome
                  sudo npm install -g yarn \
                    ember-cli
            ##
            # NPM
            ##
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: Install npm dependencies
                command: yarn install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - ./node_modules

            ##
            # TESTS
            ##
            - run:
                name: Run Ember Tests
                command: |
                  ember test

            ##
            # DEPLOYMENT
            ##
            - run: bash .circleci/setup-heroku.sh
            - add_ssh_keys:
                fingerprints:
                  - "SHA256:BggD8RSk738Q0ebf0O/wE/Hv9NktSXewS4pWlq0LuiY mwisner@Matts-MacBook-Pro-2.local"
            - run:
                name: Deploy Production (If master)
                command: |
                  if [ "${CIRCLE_BRANCH}" == "master" ]; then
                    git push heroku master
                  fi
