version: 2

jobs:
    build:
        working_directory: ~/app
        docker:
            - image: circleci/node:9.8.0-browsers
              environment:
                CHROME_BIN: "/usr/bin/google-chrome"
        steps:

            ##
            # SETUP
            ##
            - checkout

            - run:
                name: Install node global dependencies
                command: |
                  sudo npm install -g ember-cli yarn

            ##
            # NPM
            ##
            - restore_cache:
                key: dependency-cache-{{ checksum "yarn.lock" }}
            - run:
                name: Install npm dependencies
                command: yarn install
            - save_cache:
                key: dependency-cache-{{ checksum "yarn.lock" }}
                paths:
                    - ./node_modules

            ##
            # TESTS
            ### JOBS=1 ember test
            - run:
                name: Run Ember Tests
                command: JOBS=1 ember test
